name: pp_location_picker
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Puja-Purohit/pp_flutter_location_picker.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.4.0
  form_builder_extra_fields: ^10.0.0
  flutter_typeahead: ^4.6.2
  google_maps_webapi: ^0.0.22
  geolocator: ^9.0.2
  http: ^1.1.0
  logger: ^2.0.1    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: google_maps_flutter_android
      ios:
        default_package: google_maps_flutter_ios
      web:
        default_package: google_maps_flutter_web
